"""updates booking

Revision ID: 7a2b560d544d
Revises: 8c5bb5e4b0b7
Create Date: 2025-12-16 10:16:16.604149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b560d544d'
down_revision = '8c5bb5e4b0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_email_verification_tokens_email')

    with op.batch_alter_table('tattoo_appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_agreed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tattoo_appointments', schema=None) as batch_op:
        batch_op.drop_column('terms_agreed_at')

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_email_verification_tokens_email', ['email'], unique=False)

    # ### end Alembic commands ###
